import sys
import os
import pandas as pd

# Add the src directory to Python's import path for standalone execution
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../')))

from agents.data_fetcher.fetch_stock import fetch_stock_data

def calculate_indicators(df, sma_window=14, rsi_window=14):
    """
    Calculates Simple Moving Average (SMA) and Relative Strength Index (RSI).
    Adds 'SMA' and 'RSI' columns to the dataframe and drops any NaN rows created.
    """
    if df is None or df.empty:
        return df

    # Create a copy to prevent modifying the original dataframe
    df = df.copy()

    df = df[~df.index.duplicated(keep='last')]

    # Calculate Simple Moving Average (SMA) ratio
    df['SMA'] = df['Close'] / df['Close'].rolling(window=sma_window).mean()

    # Calculate Relative Strength Index (RSI)
    delta = df['Close'].diff()
    gain = delta.clip(lower=0)
    loss = -1 * delta.clip(upper=0)

    # Standard average gain/loss math using rolling mean
    avg_gain = gain.rolling(window=rsi_window).mean()
    avg_loss = loss.rolling(window=rsi_window).mean()

    rs = avg_gain / avg_loss
    df['RSI'] = 100.0 - (100.0 / (1.0 + rs))

    # Drop rows with NaN values generated by the rolling windows
    df.dropna(inplace=True)

    return df

if __name__ == "__main__":
    print("===========================================")
    print("      AI Indicator Agent Initialized       ")
    print("===========================================")
    
    ticker = input("Enter a stock ticker symbol to analyze (e.g., AAPL, RELIANCE.NS): ").strip().upper()
    
    if ticker:
        # Fetch 1 month of historical data
        data = fetch_stock_data(ticker, period="1mo")
        
        if data is not None and not data.empty:
            # Add technical indicators
            processed_data = calculate_indicators(data)
            
            if not processed_data.empty:
                print(f"\nSuccessfully calculated indicators for {ticker}!")
                print("--- Most Recent 5 Days of Data with Indicators ---")
                # Cleanly print the last 5 rows showing Close, SMA, and RSI
                columns_to_show = ['Close', 'SMA', 'RSI']
                print(processed_data[columns_to_show].tail(5).to_string())
                print("===========================================")
            else:
                print(f"\nNot enough data points to calculate 14-day SMA and RSI indicators for {ticker}.")
        else:
            print(f"\nCould not fetch valid data for {ticker}.")
    else:
        print("Input cannot be empty. Please restart the script and enter a valid ticker.")
